pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = "https://maven.neoforged.net/releases" }
    }
}

if (file("Ponder").exists()) {
    includeBuild("Ponder") {
        dependencySubstitution {
            substitute(module("net.createmod.ponder:ponder-neoforge")).using(project(":ponder-neoforge"))
            substitute(module("net.createmod.ponder:ponder-common")).using(project(":ponder-common"))
        }
    }
}

rootProject.name = "$mod_id-$minecraft_version"
